name: Bug Report
description: Report a bug or issue with Thin32 software
title: "[SOFTWARE NAME/GENERAL] BUG - "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!
        
        **Title format:** [SOFTWARE NAME/GENERAL] BUG - Small description
        Example: [Thin32 App/GENERAL] BUG - Crashes on startup
  
  - type: checkboxes
    id: duplicate-check
    attributes:
      label: Duplicate Check
      description: Please confirm you have checked for duplicate issues
      options:
        - label: I have searched existing issues and confirmed this is not a duplicate
          required: true
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true
  
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true
  
  - type: input
    id: os
    attributes:
      label: Operating System
      description: e.g. Windows 10, Windows 11
      placeholder: Windows 11
    validations:
      required: true
  
  - type: input
    id: software
    attributes:
      label: Thin32 Software
      description: Which Thin32 software are you using?
      placeholder: e.g. Thin32 App, Thin32 Tool, etc.
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Software Version
      description: Version of the specific Thin32 software you're using
      placeholder: e.g. 1.0.0
    validations:
      required: true
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the problem
      placeholder: Add any other context here...
    validations:
      required: false
