name: Question
description: Ask a question about Thin32 software
title: "[SOFTWARE NAME/GENERAL] QUESTION - "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Ask your question about Thin32!
        
        **Title format:** [SOFTWARE NAME/GENERAL] QUESTION - Small description
        Example: [Thin32 App/GENERAL] QUESTION - How to configure settings
  
  - type: checkboxes
    id: duplicate-check
    attributes:
      label: Duplicate Check
      description: Please confirm you have checked for duplicate issues
      options:
        - label: I have searched existing issues and confirmed this is not a duplicate
          required: true
  
  - type: input
    id: software
    attributes:
      label: Thin32 Software
      description: Which Thin32 software is your question about?
      placeholder: e.g. Thin32 App, Thin32 Tool, GENERAL (for all), etc.
    validations:
      required: true
  
  - type: textarea
    id: question
    attributes:
      label: Question
      description: A clear and concise question about Thin32
      placeholder: What would you like to know?
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Relevant context or background information
      placeholder: Provide context...
    validations:
      required: false
  
  - type: textarea
    id: tried
    attributes:
      label: What I've Tried
      description: What you've already tried or researched
      placeholder: I've already tried...
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Add any other information...
    validations:
      required: false
